language: python
python:
    - "3.6"
env:
    - DJANGO_SETTINGS_MODULE=django_awesome_presentations.settings
install:
    - pip install -r requirements.txt
    - pip install coverage codecov
script:
    - coverage run --source='.' manage.py test
after_success:
    - codecov
