# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_migrations', '0003_kitten'),
    ]

    operations = [
        migrations.CreateModel(
            name='KittenName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kitten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_migrations.Kitten')),
            ],
        ),
    ]
