# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 00:16
from __future__ import unicode_literals

from django.db import migrations


def migrate(apps, schema_editor):
    kitten_model = apps.get_model('testing_migrations', 'Kitten')
    kitten_name_model = apps.get_model('testing_migrations', 'KittenName')

    for kitten in kitten_model.objects.all():
        kitten_name_model.objects.create(
            kitten=kitten,
            name=kitten.name,
        )


def migrate_reverse(apps, schema_editor):
    kitten_model = apps.get_model('testing_migrations', 'Kitten')

    for kitten in kitten_model.objects.all():
        kitten.name = kitten.kittenname_set.first().name
        kitten.save()


class Migration(migrations.Migration):

    dependencies = [
        ('testing_migrations', '0004_kittenname'),
    ]

    operations = [
        migrations.RunPython(migrate, reverse_code=migrate_reverse)
    ]
