# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_migrations', '0006_blank_kitten_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitten',
            name='name',
        ),
    ]
